version: '2'
services:
  web:
    build: web/.
    restart: always
    links:
      - db:mysql
    ports:
      - "180:80"
    volumes:
    - "../blog:/var/www/html"
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devopsdemo
      MYSQL_DATABASE: devopsdemo
      MYSQL_USER: devopsdemo
      MYSQL_PASSWORD: devopsdemo
  